"""add rss category

Revision ID: 4b2e8dc4e445
Revises: 93341b81b4d8
Create Date: 2025-05-16 13:38:47.035672

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b2e8dc4e445"
down_revision: Union[str, None] = "93341b81b4d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "follow_rss_path",
        sa.Column("category_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_follow_rss_path_category_name"),
        "follow_rss_path",
        ["category_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_follow_rss_path_category_name"), table_name="follow_rss_path"
    )
    op.drop_column("follow_rss_path", "category_name")
    # ### end Alembic commands ###
